### ISSUE TITLE
Report the OAuth2 type and the user which is being impersonated

### ISSUE THREAD

**Issue by PMox** [google/gaps-support-tool#3]
GAPSTools should report these informations:
- the current OAuth2 type (3-legged or service-account)
- the user which is being impersonated

**Comment by eesheesh** [comment]
The next version will dump the registry values `ServiceAccountEmail` and `Email` (the admin email) to a file. If it's 3LO, then there's no `ServiceAccountEmail`.

**Comment by eesheesh** [comment]
Fixed in https://github.com/google/gaps-support-tool/commit/ea154c78cc73fa66f6fd9dc7d5ae64c87f51fce6.
